---
title: Various analyses I have done
author: Peter Carbonetto"
site: workflowr::wflow_site
output: workflowr::wflow_html
---

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center",dpi = 120)
```
					  
Analyses
--------

+ [Illustration of SuSiE in a "difficult" situation](susie_jrssb_example.html)

+ [There are three—not two—stationary points in the varbvs
   objective](visualize_varbvs_surface.html)

+ [Linear vs. nonlinear embeddings: a thought experiment](tsne_vs_factors.html)

+ [Exploring methods for large-scale multiple linear regression](linreg_methods_demo.html)

Other things
------------

+ [So you want to install source packages on your Mac?](r-macos.html)

+ [Multicore matrix computation in R](demo.matrix.multicore.html)

Emojis
------

Playing around with the R package [emo][emo]:

```{r emojis}
library(emo)
cat(ji("truck"),
    ji("pencil"),
    ji("pushpin"),
    ji("pig"),
	"\n")
```

You can use `emo::jis` to get the full list of the several thousand
available emojis.

[emo]: https://github.com/hadley/emo
